### ISSUE TITLE
Smallrye rest client 1.1 doesn't work when using CompletionStage and parameters

### ISSUE THREAD

**Issue by juangon** [smallrye/smallrye-rest-client#51] opened 2019-01-24 11:55 UTC
Attached a reproducer project.
[smallrye_restclient_reproducer.zip](https://github.com/smallrye/smallrye-rest-client/files/2791538/smallrye_restclient_reproducer.zip)

When using SmallRye restclient asynchronously (added in MP Rest client 1.1), it doesn't work if there are parameters in the request, throwing this error: 

> RESTEASY003720: path param name has not been provided by the parameter map

when using code like this:

```java
@Path("/api/hello")
@RequestScoped
@RegisterRestClient
public interface HelloService {

    @GET
    @Path("{name}")
    @Produces(TEXT_PLAIN)
    @Consumes(TEXT_PLAIN)
    CompletionStage<String> helloAsync(@PathParam("name") String name);

}

```

**Comment by michalszynkiewicz** [comment] 2019-02-26 11:04
It is a problem with Resteasy that is not simple (if possible at all) to workaround in SmallRye.
The cause: https://issues.jboss.org/browse/RESTEASY-2139

**Comment by juangon** [comment] 2019-02-27 09:19
Oh, bad news :-(

**Comment by kenfinnigan** [comment] 2019-05-30 18:23
Closing as implementation has been moved to https://github.com/resteasy/Resteasy/tree/master/resteasy-client-microprofile

**Closed by kenfinnigan** 2019-05-30 18:23 UTC
